// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication_0919.Models.EFModels;

public partial class Order
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public int Total { get; set; }

    public DateTime CreatedTime { get; set; }

    public int Status { get; set; }

    public bool RequestRefund { get; set; }

    public DateTime? RequestRefundTime { get; set; }

    public string Receiver { get; set; }

    public string Address { get; set; }

    public string CellPhone { get; set; }

    public virtual Member Member { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();
}